name: paysheet_example
description: Example app demonstrating the paysheet package
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  paysheet:
    path: ../

flutter:
  uses-material-design: true
